# Generated by Django 4.2.4 on 2023-08-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otherpages', '0005_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('image', models.CharField(max_length=200)),
            ],
        ),
    ]
