# Generated by Django 4.2.4 on 2023-08-18 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otherpages', '0006_blog_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_slider',
            name='image',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
