# Generated by Django 4.2.4 on 2023-08-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_header_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('diss', models.TextField()),
                ('body', models.TextField()),
                ('image', models.CharField(max_length=200)),
            ],
        ),
    ]
