# Generated by Django 4.2.4 on 2023-08-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('image', models.CharField(max_length=200)),
            ],
        ),
    ]
